// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP5mOJR0xN0MjtlqpYc2DgPFojyQ4DzGk',
    appId: '1:592507481594:web:352de416793fed3351c843',
    messagingSenderId: '592507481594',
    projectId: 'chat-app-835df',
    authDomain: 'chat-app-835df.firebaseapp.com',
    storageBucket: 'chat-app-835df.firebasestorage.app',
    measurementId: 'G-L35QJHHREV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBK8kFL0B9dfhqy_me712KrOp4bHnz9Ms',
    appId: '1:592507481594:android:d0030d5ca387234a51c843',
    messagingSenderId: '592507481594',
    projectId: 'chat-app-835df',
    storageBucket: 'chat-app-835df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOcyHjA-SGXiOLnpAPRGTfjqYYyxz8_gc',
    appId: '1:592507481594:ios:960eef686a41914c51c843',
    messagingSenderId: '592507481594',
    projectId: 'chat-app-835df',
    storageBucket: 'chat-app-835df.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOcyHjA-SGXiOLnpAPRGTfjqYYyxz8_gc',
    appId: '1:592507481594:ios:960eef686a41914c51c843',
    messagingSenderId: '592507481594',
    projectId: 'chat-app-835df',
    storageBucket: 'chat-app-835df.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP5mOJR0xN0MjtlqpYc2DgPFojyQ4DzGk',
    appId: '1:592507481594:web:6e1f973cac2a1a0b51c843',
    messagingSenderId: '592507481594',
    projectId: 'chat-app-835df',
    authDomain: 'chat-app-835df.firebaseapp.com',
    storageBucket: 'chat-app-835df.firebasestorage.app',
    measurementId: 'G-30GBRPR9D5',
  );
}
